In [1]:
import numpy as np # numpy a.k.a numerical python is particularly useful when dealing with arrays

In [2]:
l = [1,2,3,4]

In [3]:
type(l)

list

In [4]:
# you can convert a list to an array
arr = np.array(l)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

In [10]:
a1 = np.array([l,l]) # creating a 2d array

In [11]:
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [13]:
arr.ndim # checking the number of dimensions an array has

1

In [14]:
a1.ndim

2

In [15]:
#introducing matrices
m = np.matrix(l)

In [16]:
m #matrices are a form of array which have a min of 2 diensions

matrix([[1, 2, 3, 4]])

In [17]:
np.asanyarray(l) #another function for converting objects into arrays

array([1, 2, 3, 4])

In [18]:
np.asanyarray(m) # a matrix is a type of array so this function does not alter it

matrix([[1, 2, 3, 4]])

In [19]:
a = arr

In [20]:
a

array([1, 2, 3, 4])

In [21]:
arr[0] = 66

In [22]:
arr

array([66,  2,  3,  4])

In [23]:
a # phenomenon known as a shallow copy i.e. it is just a refernce to arr so if it changes, a changes

array([66,  2,  3,  4])

In [26]:
a[1] = 33

In [27]:
a

array([66, 33,  3,  4])

In [28]:
arr

array([66, 33,  3,  4])

In [24]:
b = np.copy(arr)

In [25]:
b

array([66,  2,  3,  4])

In [29]:
arr[0] = 99

In [30]:
arr

array([99, 33,  3,  4])

In [31]:
b # phenomenon known as deep copy, a change in arr has no effect on b

array([66,  2,  3,  4])

In [32]:
# creating an array from functions
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j: i*j, (4,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.],
       [0., 3., 6.]])

In [45]:
#creating an array from an iterable object
it = (i*2 for i in range(5))

In [46]:
it

<generator object <genexpr> at 0x000001E5D5E253C0>

In [47]:
list(it)

[0, 2, 4, 6, 8]

In [48]:
#creating an array from an iterable object
np.fromiter(it, float)

array([], dtype=float64)

In [49]:
# creating an array from a string with a common seperator
np.fromstring('1 2 4 88', sep = ' ')

array([ 1.,  2.,  4., 88.])

In [50]:
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [51]:
arr

array([99, 33,  3,  4])

In [53]:
a1.ndim

2

In [54]:
arr.ndim

1

In [55]:
a1.size #number of elements in the array

8

In [56]:
arr.size #number of elements in the array

4

In [57]:
a1.shape 

(2, 4)

In [58]:
arr.shape

(4,)

In [60]:
a1.dtype # data type held in array

dtype('int32')

In [61]:
np.array(['a',1,2])

array(['a', '1', '2'], dtype='<U1')

In [2]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [4]:
list(range(0.1,3.5)) # the range function only works with integrs

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
np.arange(0.4,5.6,0.4) #np.arange is an alternative to the range function which works with decimal

array([0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2])

In [6]:
list(np.arange(0.4,5.6,0.4)) # you can then convert it to a list if needed

[0.4,
 0.8,
 1.2000000000000002,
 1.6,
 2.0,
 2.4,
 2.8000000000000003,
 3.2,
 3.6,
 4.0,
 4.4,
 4.800000000000001,
 5.200000000000001]

In [7]:
np.linspace(1,5, 20) # divide the range between 1 and 5 into 20 equal parts

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [9]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [10]:
np.zeros(5) # generates an array made up of zeros

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
np.ones(5) # generates an array made up of 1's

array([1., 1., 1., 1., 1.])

In [18]:
a = np.ones((3,4))

In [19]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
a+5 # adds 5  to every element in the array

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [23]:
a*199 # multiplies every element by 199

array([[199., 199., 199., 199.],
       [199., 199., 199., 199.],
       [199., 199., 199., 199.]])

In [24]:
np.empty((3,4))

array([[199., 199., 199., 199.],
       [199., 199., 199., 199.],
       [199., 199., 199., 199.]])

In [25]:
np.empty((3,4,2))

array([[[6.23042070e-307, 4.67296746e-307],
        [1.69121096e-306, 9.34597568e-307],
        [7.56587584e-307, 1.37961302e-306],
        [1.05699242e-307, 8.01097889e-307]],

       [[1.78020169e-306, 7.56601165e-307],
        [1.02359984e-306, 1.33510679e-306],
        [2.22522597e-306, 1.78019761e-306],
        [1.37962185e-306, 1.78019625e-306]],

       [[6.89812281e-307, 9.34609790e-307],
        [1.24610723e-306, 1.05700515e-307],
        [1.11261774e-306, 1.29060871e-306],
        [8.34424766e-308, 2.12203497e-312]]])

In [26]:
a1 = np.eye(2) #creates a 2x2 dimensional identity array

In [27]:
a1

array([[1., 0.],
       [0., 1.]])

In [28]:
a1 = np.eye(5) #creates a 5x5 dimensional identity array

In [29]:
a1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
import pandas as pd

In [32]:
# you can convert any array to a dataframe
pd.DataFrame(a1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [33]:
np.random.rand(3) #generates a random array based on the shape specified

array([0.9206423 , 0.63913547, 0.77114019])

In [34]:
np.random.rand(3,4) #generates a random array based on the shape specified

array([[0.15767488, 0.40571216, 0.17532161, 0.86868084],
       [0.47708347, 0.23901081, 0.22617626, 0.24103353],
       [0.72473406, 0.9654084 , 0.72525348, 0.11256047]])

In [35]:
np.random.randn(3,4) #generates a random array with mean = 0  and standard deviation of 1
# i.e. using standard normal distribution

array([[-1.39176777,  1.8082314 , -1.13998433,  0.75536079],
       [-0.39372105, -0.50977958,  0.85064917, -0.38689532],
       [ 1.09563359, -0.7839106 , -0.08493496, -0.98198016]])

In [37]:
a2 = np.random.randint(1,99, (2,4)) #create a 2x4 array with nimbers between 1 and 99

In [38]:
a2

array([[33, 33, 45, 80],
       [27, 66, 50, 46]])

In [39]:
a2.size

8

In [40]:
a2.shape

(2, 4)

In [42]:
# you can change the shape of the array
a2.reshape(1,8)

array([[33, 33, 45, 80, 27, 66, 50, 46]])

In [43]:
# you can change the shape of the array
a2.reshape(4,2)

array([[33, 33],
       [45, 80],
       [27, 66],
       [50, 46]])

In [44]:
a2.reshape(4,4) # you cannot reshape into an array with a bigger size

ValueError: cannot reshape array of size 8 into shape (4,4)

In [45]:
a2.reshape(2,2,2)

array([[[33, 33],
        [45, 80]],

       [[27, 66],
        [50, 46]]])

In [46]:
a2 = np.random.randint(1,60, (2,4)) 

In [47]:
a2

array([[56, 36, 34, 26],
       [36, 21, 47,  6]])

In [48]:
a2<30 # returns true where data in the position meets the condition

array([[False, False, False,  True],
       [False,  True, False,  True]])

In [52]:
a2[a2<30] # give me the values which match my condition

array([26, 21,  6])

In [57]:
a2[1,2:] #extracting data from an array

array([47,  6])

In [59]:
a2[0,[1,2]] #extract (0,1) and (0,2)

array([36, 34])

In [71]:
a2 = np.random.randint(1,60, (5,5)) 

In [72]:
a2

array([[41, 31,  4, 40, 28],
       [52,  3, 11, 27, 23],
       [23, 18,  9,  4, 38],
       [51, 29, 12, 40, 52],
       [34, 50, 54, 10, 25]])

In [73]:
a2[1:3,2:4]

array([[11, 27],
       [ 9,  4]])

In [74]:
a4  = np.random.randint(1,60, (5,5)) 

In [75]:
a4

array([[30,  6, 50, 38, 10],
       [51, 40, 28, 28, 22],
       [48, 27, 20, 41, 28],
       [50, 46, 56,  1, 36],
       [11, 26, 36, 22,  4]])

In [76]:
a4+a2

array([[ 71,  37,  54,  78,  38],
       [103,  43,  39,  55,  45],
       [ 71,  45,  29,  45,  66],
       [101,  75,  68,  41,  88],
       [ 45,  76,  90,  32,  29]])

In [77]:
a3 = np.random.randint(1,60, (2,5)) 

In [78]:
a4+a3 # same as matrix addition

ValueError: operands could not be broadcast together with shapes (5,5) (2,5) 

In [79]:
a4-a2 # same as matrix subtraction

array([[-11, -25,  46,  -2, -18],
       [ -1,  37,  17,   1,  -1],
       [ 25,   9,  11,  37, -10],
       [ -1,  17,  44, -39, -16],
       [-23, -24, -18,  12, -21]])

In [80]:
a4*a2 # does an index wise multiplication

array([[1230,  186,  200, 1520,  280],
       [2652,  120,  308,  756,  506],
       [1104,  486,  180,  164, 1064],
       [2550, 1334,  672,   40, 1872],
       [ 374, 1300, 1944,  220,  100]])

In [81]:
# for a matrix multiplication
a4@a2

array([[4970, 3450, 1632, 3182, 5104],
       [6991, 4117, 2420, 4572, 5418],
       [6875, 4518, 2673, 4649, 5557],
       [7005, 4525, 3166, 3866, 5538],
       [3889, 1905, 1134, 2206, 3518]])

In [82]:
a4/a2 # does an index wise division

array([[ 0.73170732,  0.19354839, 12.5       ,  0.95      ,  0.35714286],
       [ 0.98076923, 13.33333333,  2.54545455,  1.03703704,  0.95652174],
       [ 2.08695652,  1.5       ,  2.22222222, 10.25      ,  0.73684211],
       [ 0.98039216,  1.5862069 ,  4.66666667,  0.025     ,  0.69230769],
       [ 0.32352941,  0.52      ,  0.66666667,  2.2       ,  0.16      ]])

In [83]:
(a4@a2)/0

<ipython-input-83-7ed048b98bd6>:1: RuntimeWarning: divide by zero encountered in true_divide
  (a4@a2)/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [84]:
a5 = np.zeros((5,5))

In [85]:
a5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [86]:
# Array broadcasting
a5+88 #8 has been broadcasted to a5

array([[88., 88., 88., 88., 88.],
       [88., 88., 88., 88., 88.],
       [88., 88., 88., 88., 88.],
       [88., 88., 88., 88., 88.],
       [88., 88., 88., 88., 88.]])

In [87]:
a2

array([[41, 31,  4, 40, 28],
       [52,  3, 11, 27, 23],
       [23, 18,  9,  4, 38],
       [51, 29, 12, 40, 52],
       [34, 50, 54, 10, 25]])

In [88]:
a5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [89]:
a2 +a5

array([[41., 31.,  4., 40., 28.],
       [52.,  3., 11., 27., 23.],
       [23., 18.,  9.,  4., 38.],
       [51., 29., 12., 40., 52.],
       [34., 50., 54., 10., 25.]])

In [99]:
b = np.array([1,2,5,7,3])

In [100]:
a5+b

array([[1., 2., 5., 7., 3.],
       [1., 2., 5., 7., 3.],
       [1., 2., 5., 7., 3.],
       [1., 2., 5., 7., 3.],
       [1., 2., 5., 7., 3.]])

In [101]:
b1 = np.array([[1,2,3,5,7]])

In [102]:
a5+b1

array([[1., 2., 3., 5., 7.],
       [1., 2., 3., 5., 7.],
       [1., 2., 3., 5., 7.],
       [1., 2., 3., 5., 7.],
       [1., 2., 3., 5., 7.]])

In [103]:
#to add you need to transpose b1 then it will do a row wise addition 
b1.T

array([[1],
       [2],
       [3],
       [5],
       [7]])

In [104]:
a5 + b1.T

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5.],
       [7., 7., 7., 7., 7.]])

In [107]:
np.sqrt(a2) #element wise square root

array([[6.40312424, 5.56776436, 2.        , 6.32455532, 5.29150262],
       [7.21110255, 1.73205081, 3.31662479, 5.19615242, 4.79583152],
       [4.79583152, 4.24264069, 3.        , 2.        , 6.164414  ],
       [7.14142843, 5.38516481, 3.46410162, 6.32455532, 7.21110255],
       [5.83095189, 7.07106781, 7.34846923, 3.16227766, 5.        ]])

In [108]:
np.log(a2) #element wise log 

array([[3.71357207, 3.4339872 , 1.38629436, 3.68887945, 3.33220451],
       [3.95124372, 1.09861229, 2.39789527, 3.29583687, 3.13549422],
       [3.13549422, 2.89037176, 2.19722458, 1.38629436, 3.63758616],
       [3.93182563, 3.36729583, 2.48490665, 3.68887945, 3.95124372],
       [3.52636052, 3.91202301, 3.98898405, 2.30258509, 3.21887582]])

In [109]:
np.exp(a) #element wise exponent

array([[2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183]])

In [110]:
np.max(a2) # return highest number in the array

54

In [112]:
np.min(a2) #return lowest number in the array

3

In [2]:
a = np.random.randint(1,60, (4,4)) 

In [4]:
a

array([[31, 19,  7,  4],
       [ 5,  8, 46, 53],
       [46, 25, 44, 21],
       [45, 13, 29, 31]])

In [3]:
#transposing an array
a.T

array([[31,  5, 46, 45],
       [19,  8, 25, 13],
       [ 7, 46, 44, 29],
       [ 4, 53, 21, 31]])

In [5]:
# reduce your array to a 1D array
a.flatten()

array([31, 19,  7,  4,  5,  8, 46, 53, 46, 25, 44, 21, 45, 13, 29, 31])

In [6]:
np.expand_dims(a,axis = 0) # will add an additional dimennsion row wise

array([[[31, 19,  7,  4],
        [ 5,  8, 46, 53],
        [46, 25, 44, 21],
        [45, 13, 29, 31]]])

In [8]:
np.expand_dims(a,axis = 1) # will add an additional dimennsion column wise

array([[[31, 19,  7,  4]],

       [[ 5,  8, 46, 53]],

       [[46, 25, 44, 21]],

       [[45, 13, 29, 31]]])

In [11]:
a1 = np.array([[1],[20], [3]])

In [12]:
a1

array([[ 1],
       [20],
       [ 3]])

In [13]:
np.squeeze(a1) #reducing the dimension of an array

array([ 1, 20,  3])

In [15]:
np.repeat(a1,3) # repeat each element 3 times and return as a 1d

array([ 1,  1,  1, 20, 20, 20,  3,  3,  3])

In [16]:
np.repeat(a,3) # repeat each element 3 times and return as a 1d

array([31, 31, 31, 19, 19, 19,  7,  7,  7,  4,  4,  4,  5,  5,  5,  8,  8,
        8, 46, 46, 46, 53, 53, 53, 46, 46, 46, 25, 25, 25, 44, 44, 44, 21,
       21, 21, 45, 45, 45, 13, 13, 13, 29, 29, 29, 31, 31, 31])

In [19]:
np.roll(a,2,0) #move each row 2 steps vertically (row wise)

array([[46, 25, 44, 21],
       [45, 13, 29, 31],
       [31, 19,  7,  4],
       [ 5,  8, 46, 53]])

In [20]:
np.roll(a,2,1) #move each row 2 steps horizontally (column wise)

array([[ 7,  4, 31, 19],
       [46, 53,  5,  8],
       [44, 21, 46, 25],
       [29, 31, 45, 13]])

In [21]:
np.diag(np.array([1,2,3,4])) #place values in the diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
a

array([[31, 19,  7,  4],
       [ 5,  8, 46, 53],
       [46, 25, 44, 21],
       [45, 13, 29, 31]])

In [29]:
a.T

array([[31,  5, 46, 45],
       [19,  8, 25, 13],
       [ 7, 46, 44, 29],
       [ 4, 53, 21, 31]])

In [26]:
a**2

array([[ 961,  361,   49,   16],
       [  25,   64, 2116, 2809],
       [2116,  625, 1936,  441],
       [2025,  169,  841,  961]], dtype=int32)

In [27]:
~a

array([[-32, -20,  -8,  -5],
       [ -6,  -9, -47, -54],
       [-47, -26, -45, -22],
       [-46, -14, -30, -32]], dtype=int32)

In [28]:
a+a.T

array([[62, 24, 53, 49],
       [24, 16, 71, 66],
       [53, 71, 88, 50],
       [49, 66, 50, 62]])

In [30]:
a>a.T

array([[False,  True, False, False],
       [False, False,  True,  True],
       [ True, False, False, False],
       [ True, False,  True, False]])

In [31]:
a-a.T

array([[  0,  14, -39, -41],
       [-14,   0,  21,  40],
       [ 39, -21,   0,  -8],
       [ 41, -40,   8,   0]])

In [41]:
a**a.T # a to power a.T index wise

TypeError: ufunc 'power' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### String operations

In [33]:
a = np.array(['ope', 'costa'])

In [34]:
a

array(['ope', 'costa'], dtype='<U5')

In [35]:
np.char.upper(a) # capitalize characters

array(['OPE', 'COSTA'], dtype='<U5')

In [36]:
np.char.capitalize(a) # capitalize first letters

array(['Ope', 'Costa'], dtype='<U5')

In [37]:
np.char.title(a)

array(['Ope', 'Costa'], dtype='<U5')

In [38]:
a1 = np.array([1,'ope', True])

In [39]:
a1 # see how data type of everything is now a string

array(['1', 'ope', 'True'], dtype='<U11')

In [40]:
np.char.upper(a1)

array(['1', 'OPE', 'TRUE'], dtype='<U11')

### Numerical operations

In [42]:
a = np.random.randint(1,60, (4,4)) 

In [43]:
a

array([[26,  4, 23, 23],
       [28, 14, 17, 54],
       [22, 18, 17, 45],
       [15, 54, 54, 55]])

In [44]:
np.sin(a) # note this is radian

array([[ 0.76255845, -0.7568025 , -0.8462204 , -0.8462204 ],
       [ 0.27090579,  0.99060736, -0.96139749, -0.55878905],
       [-0.00885131, -0.75098725, -0.96139749,  0.85090352],
       [ 0.65028784, -0.55878905, -0.55878905, -0.99975517]])

In [45]:
np.tan(a)

array([[ 1.17875355e+00,  1.15782128e+00,  1.58815308e+00,
         1.58815308e+00],
       [-2.81429605e-01,  7.24460662e+00,  3.49391565e+00,
         6.73800101e-01],
       [ 8.85165604e-03, -1.13731371e+00,  3.49391565e+00,
         1.61977519e+00],
       [-8.55993401e-01,  6.73800101e-01,  6.73800101e-01,
        -4.51830879e+01]])

In [46]:
np.log10(a)

array([[1.41497335, 0.60205999, 1.36172784, 1.36172784],
       [1.44715803, 1.14612804, 1.23044892, 1.73239376],
       [1.34242268, 1.25527251, 1.23044892, 1.65321251],
       [1.17609126, 1.73239376, 1.73239376, 1.74036269]])

In [47]:
np.exp(a)

array([[1.95729609e+11, 5.45981500e+01, 9.74480345e+09, 9.74480345e+09],
       [1.44625706e+12, 1.20260428e+06, 2.41549528e+07, 2.83075330e+23],
       [3.58491285e+09, 6.56599691e+07, 2.41549528e+07, 3.49342711e+19],
       [3.26901737e+06, 2.83075330e+23, 2.83075330e+23, 7.69478527e+23]])

In [48]:
a

array([[26,  4, 23, 23],
       [28, 14, 17, 54],
       [22, 18, 17, 45],
       [15, 54, 54, 55]])

In [49]:
np.power(a,4) # each element of array to power of 4

array([[ 456976,     256,  279841,  279841],
       [ 614656,   38416,   83521, 8503056],
       [ 234256,  104976,   83521, 4100625],
       [  50625, 8503056, 8503056, 9150625]], dtype=int32)

In [50]:
np.mean(a) # mean of entire array

29.3125

In [51]:
np.median(a) # median

23.0

In [53]:
np.std(a) # standard deviation

16.566980526034307

In [54]:
np.var(a) #variance

274.46484375

In [55]:
np.min(a) # smallest number in a 

4

In [56]:
np.max(a) # largest number in a

55

In [57]:
a-a.T

array([[  0, -24,   1,   8],
       [ 24,   0,  -1,   0],
       [ -1,   1,   0,  -9],
       [ -8,   0,   9,   0]])

In [59]:
np.subtract(a,a.T) # does same as above

array([[  0, -24,   1,   8],
       [ 24,   0,  -1,   0],
       [ -1,   1,   0,  -9],
       [ -8,   0,   9,   0]])

In [60]:
a*a.T

array([[ 676,  112,  506,  345],
       [ 112,  196,  306, 2916],
       [ 506,  306,  289, 2430],
       [ 345, 2916, 2430, 3025]])

In [61]:
np.multiply(a,a.T) 

array([[ 676,  112,  506,  345],
       [ 112,  196,  306, 2916],
       [ 506,  306,  289, 2430],
       [ 345, 2916, 2430, 3025]])

In [62]:
a**5

array([[ 11881376,      1024,   6436343,   6436343],
       [ 17210368,    537824,   1419857, 459165024],
       [  5153632,   1889568,   1419857, 184528125],
       [   759375, 459165024, 459165024, 503284375]], dtype=int32)

In [63]:
np.power(a,5)

array([[ 11881376,      1024,   6436343,   6436343],
       [ 17210368,    537824,   1419857, 459165024],
       [  5153632,   1889568,   1419857, 184528125],
       [   759375, 459165024, 459165024, 503284375]], dtype=int32)

In [65]:
np.sqrt(a)

array([[5.09901951, 2.        , 4.79583152, 4.79583152],
       [5.29150262, 3.74165739, 4.12310563, 7.34846923],
       [4.69041576, 4.24264069, 4.12310563, 6.70820393],
       [3.87298335, 7.34846923, 7.34846923, 7.41619849]])

In [66]:
a

array([[26,  4, 23, 23],
       [28, 14, 17, 54],
       [22, 18, 17, 45],
       [15, 54, 54, 55]])

In [6]:
w = np.array([4,5,7,1,66,22,54,67,12])

In [10]:
w

array([ 4,  5,  7,  1, 66, 22, 54, 67, 12])

In [11]:
#sorting an array
np.sort(w)

array([ 1,  4,  5,  7, 12, 22, 54, 66, 67])

In [20]:
np.searchsorted(w,61)

4

In [21]:
np.count_nonzero(w) # number of elements that are not 0

9

In [22]:
np.where(w<44) # return index of elements whuch meet the condition

(array([0, 1, 2, 3, 5, 8], dtype=int64),)

In [26]:
np.extract(w<44,w) # return list of elements whuch meet the condition

array([ 4,  5,  7,  1, 22, 12])

In [27]:
y = w.view() # similar to a shallow copy i.e. y = w

In [28]:
y

array([ 4,  5,  7,  1, 66, 22, 54, 67, 12])

In [29]:
w

array([ 4,  5,  7,  1, 66, 22, 54, 67, 12])

In [30]:
y[1] = 66

In [31]:
w #change affects both y and w

array([ 4, 66,  7,  1, 66, 22, 54, 67, 12])

In [32]:
y

array([ 4, 66,  7,  1, 66, 22, 54, 67, 12])

In [33]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Numpy - Matrix Library

In [35]:
import numpy.matlib as nm # fro dealing with matrices

In [36]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [39]:
nm.ones((5,6))

matrix([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [40]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [44]:
x  = np.random.randint([[1,60], [50,5]])

In [45]:
x

array([[ 0, 33],
       [40,  2]])

In [46]:
x1  = np.random.randint([[1,6], [50,5]])

In [47]:
x1

array([[0, 1],
       [4, 4]])

In [49]:
np.dot(x,x1) # dot product

array([[132, 132],
       [  8,  48]])